import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import ConfigureAmplifyClientSide from "./amplify-cognito-config";
import "./globals.css";

const roboto_init = Roboto({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

       <body className={`${roboto_init.variable} antialiased`}>
        <>
          <ConfigureAmplifyClientSide />
          {children}
        </>
      </body>
    </html>
  );
}
